# Copyright (C) 2026 Georgi Danovski
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Disable bootloader support, as the bootloader is not used in this project
CONFIG_BOARD_HAS_NRF5_BOOTLOADER=n

# Enable RTT console support and logging
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y

# Enable zephyr modules
CONFIG_PWM=y
CONFIG_SENSOR=y
CONFIG_ADC=y

# Enable BLE stack
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP=y
CONFIG_BT_BONDABLE=y
CONFIG_BT_SETTINGS=y
CONFIG_BT_FILTER_ACCEPT_LIST=y
CONFIG_BT_DEVICE_NAME="Quadruped"
CONFIG_BT_DEVICE_APPEARANCE=0
CONFIG_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y

# Enable project modules
CONFIG_LEG_MODULE=y
CONFIG_QUADRUPED_MODULE=y
CONFIG_VOLTAGE_REGULATOR_MODULE=y
CONFIG_MOVE_CONTROLLER_MODULE=y
CONFIG_MEASUREMENTS_MODULE=y
CONFIG_BLE_PERIPHERAL_MODULE=y
